### ISSUE TITLE
Keksbot cannot take over the world

### ISSUE THREAD

**Issue by vehk** [cookiemon/Keksbot#10]
Via cce6802.

Please remove the offending commit immediately.

**Comment by cookiemon** [comment]
If he can't anyway, there is no harm in leaving it.

**Comment by vehk** [comment]
Are you saying the possibility of world domination was ever implemented in the first place?

**Comment by cookiemon** [comment]
Keksbot was never intended to take over the world and this commit is just to ensure it never will happen.

**Comment by vehk** [comment]
What a shame. I am truly saddened by this revelation.

**Comment by vehk** [comment]
This issue can be closed. I shall implement my own bot. Thank you for your cooperation. Rest in peace.
